# Generated by Django 5.0.6 on 2024-06-27 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('pk_id_alerta', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'alerta',
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('pk_id_carrera', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'carrera',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('pk_id_estado', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'estado',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('pk_id_horario', models.BigAutoField(primary_key=True, serialize=False)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'db_table': 'horario',
            },
        ),
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('pk_id_campo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('aforo', models.IntegerField()),
                ('fk_id_estado', models.ForeignKey(db_column='fk_id_estado', on_delete=django.db.models.deletion.DO_NOTHING, to='apiProyect.estado')),
            ],
            options={
                'db_table': 'campo',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('pk_id_rol', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('pk_id_estado', models.ForeignKey(db_column='pk_id_estado', on_delete=django.db.models.deletion.DO_NOTHING, to='apiProyect.estado')),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('pk_id_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('nombres', models.CharField(max_length=255)),
                ('codigo_tecsup', models.CharField(max_length=255)),
                ('fk_id_carrera', models.ForeignKey(blank=True, db_column='fk_id_carrera', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apiProyect.carrera')),
                ('fk_id_estado', models.ForeignKey(db_column='fk_id_estado', on_delete=django.db.models.deletion.DO_NOTHING, to='apiProyect.estado')),
                ('fk_id_rol', models.ForeignKey(db_column='fk_id_rol', on_delete=django.db.models.deletion.DO_NOTHING, to='apiProyect.rol')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('pk_id_reserva', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('comentario', models.CharField(blank=True, max_length=255, null=True)),
                ('fk_id_campo', models.ForeignKey(db_column='fk_id_campo', on_delete=django.db.models.deletion.DO_NOTHING, to='apiProyect.campo')),
                ('fk_id_estado', models.ForeignKey(db_column='fk_id_estado', on_delete=django.db.models.deletion.DO_NOTHING, to='apiProyect.estado')),
                ('fk_id_horario', models.ForeignKey(db_column='fk_id_horario', on_delete=django.db.models.deletion.DO_NOTHING, to='apiProyect.horario')),
                ('fk_id_usuario', models.ForeignKey(db_column='fk_id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='apiProyect.usuario')),
            ],
            options={
                'db_table': 'reserva',
            },
        ),
    ]
